language: rust
dist: xenial
rust:
  - nightly

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - upx-ucl

env:
  - CC=gcc-8 CXX=g++-8

script:
  - 'cargo build --all --verbose'
  - 'cargo test --all --verbose'
cache: cargo
