language: rust
dist: xenial
rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

env:
  - CC=gcc-7
  - CXX=g++-7

script:
  - 'cargo build --all --verbose'
  - 'cargo test --all --verbose'
cache: cargo
