[package]
name = "dpsp-libp2p"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
async-std = "1.8.0"
async-trait = "0.1.42"
dprun = { path = "../dprun" }
futures = "0.3.10"
libp2p = "0.31.2"
log = "0.4.13"
