[package]
name = "dpsp-libp2p"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
dprun = { path = "../dprun" }
libp2p = "^0.13.0"
futures = "^0.1.29"
tokio = "^0.1.0"
