[package]
name = "dpsp-libp2p"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
async-std = "1.6.5"
async-trait = "0.1.40"
dprun = { path = "../dprun" }
futures = "0.3.5"
libp2p = "0.28.1"
log = "0.4.11"
