[package]
name = "aoc-spectate"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
async-std = "0.99"
futures-preview = { version = "0.3.0-alpha.18", features = [ "async-await", "nightly" ] }
